# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2021.2.1\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2021.2.1\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\User\Documents\University\Third Year Uni\320\Group\TanksPlusPlus"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\User\Documents\University\Third Year Uni\320\Group\TanksPlusPlus"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2021.2.1\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2021.2.1\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\User\Documents\University\Third Year Uni\320\Group\TanksPlusPlus\CMakeFiles" "C:\Users\User\Documents\University\Third Year Uni\320\Group\TanksPlusPlus\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\User\Documents\University\Third Year Uni\320\Group\TanksPlusPlus\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TanksPlusPlus

# Build rule for target.
TanksPlusPlus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 TanksPlusPlus
.PHONY : TanksPlusPlus

# fast build rule for target.
TanksPlusPlus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/build
.PHONY : TanksPlusPlus/fast

Game.obj: Game.cpp.obj
.PHONY : Game.obj

# target to build an object file
Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Game.cpp.obj
.PHONY : Game.cpp.obj

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Game.cpp.s
.PHONY : Game.cpp.s

MainMenu.obj: MainMenu.cpp.obj
.PHONY : MainMenu.obj

# target to build an object file
MainMenu.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/MainMenu.cpp.obj
.PHONY : MainMenu.cpp.obj

MainMenu.i: MainMenu.cpp.i
.PHONY : MainMenu.i

# target to preprocess a source file
MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/MainMenu.cpp.i
.PHONY : MainMenu.cpp.i

MainMenu.s: MainMenu.cpp.s
.PHONY : MainMenu.s

# target to generate assembly for a file
MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/MainMenu.cpp.s
.PHONY : MainMenu.cpp.s

Player.obj: Player.cpp.obj
.PHONY : Player.obj

# target to build an object file
Player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Player.cpp.obj
.PHONY : Player.cpp.obj

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Player.cpp.s
.PHONY : Player.cpp.s

Wall.obj: Wall.cpp.obj
.PHONY : Wall.obj

# target to build an object file
Wall.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Wall.cpp.obj
.PHONY : Wall.cpp.obj

Wall.i: Wall.cpp.i
.PHONY : Wall.i

# target to preprocess a source file
Wall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Wall.cpp.i
.PHONY : Wall.cpp.i

Wall.s: Wall.cpp.s
.PHONY : Wall.s

# target to generate assembly for a file
Wall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/Wall.cpp.s
.PHONY : Wall.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TanksPlusPlus.dir\build.make CMakeFiles/TanksPlusPlus.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... TanksPlusPlus
	@echo ... Game.obj
	@echo ... Game.i
	@echo ... Game.s
	@echo ... MainMenu.obj
	@echo ... MainMenu.i
	@echo ... MainMenu.s
	@echo ... Player.obj
	@echo ... Player.i
	@echo ... Player.s
	@echo ... Wall.obj
	@echo ... Wall.i
	@echo ... Wall.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

